language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - echo "skipping tests"

deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  password:
    secure: GWnSzI2Ewb8hLlFko4dgUNska7egwmHG/xiSq/u+ZQGTZ8T+gE7S9G6OvZVaduc3tfwSlIUwK0lLmBXmuwWBUeSjZhBpSIwUFagWc5UhMh98ZcbQkWj4Rb7oGrucgV7+IveGqRWUlQDsHmf1uXmOVuRQOEUyUPoa/bKuf/EJXf31Uug42LSY2B0xPLaNqTK0BNV8ZaM6eRphHpx/2opQPOH4kZbY+xnqlU1M4xEyiCqgARQpR9B1uENNcXN4t2/KIYILKZ3MGv/m3+YJQsI0wlofzIKpGeZVo2PkD/wagR2E995loRSzaj3EHZoa4c9zTAq0qLd7sQNfjIml+WdX3YDwHHcHANiipQLjajEuXy5e6FOj1O/Y9uAQmUfxfEUgyQRZnap61sR+s2lT15+ulkV0pCU906lA/gWVf0gftrlhdAqwmt5QNgQNKU2GpZPnGOi4fLxbBHpWTOW2PznJPgsNE1Cb/sRdPrCacLafL5Ix1EnP5rZfJkiN28t1BU628/r110INA+iw5jY7b1ZnSsazErkJzt9raRgiFnsE3JC+gxsLjwFJVl6AwJzGjwpvDz0a1myN8dQe3b5BMXGJuYP1aj5adRcLMB64Fyipfp13nR7A2UpvXqgmbrEr+tdDvoAXTLokS0aO9AjzG6tuNS+bPWPC44LDOW8m5N9eo0o=

  on:
    tags: true
