language: python
python:
- '2.7'
- '3.6'
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install .
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  password:
    secure: lQspZf59dwI+Y1ySyey2jzOcithTkmai392VbcdyrciK14kpuTeWcMzFQNOv5Qf6IyQBIVrNNDIJ75ga/s97KIO59E/XDqo+s1pSfOGjvHXHmzTT6tBiZQtM2qiTPUpo+8G8Y+4SN8Z+wMpFj8+oigfR3kmRjhg4k4GSUgN29hXQo3ZR2qfLGo6Oh10J9J+iSVpnsi9cWVFREV9L9iGrFKX8g3gdQkOPAzh2xaCk6v+mvsO89O1T6j1uyL8tmnq7BFMYQ5RRW3ze0ieajIMOeOkpd20w/wXecrTKNOhZTn4qIJONZkKeRlfXS1DGQmnj7HScESYG4Q0oapsMgGPq3WEdSbu8OMCoJBCTVH+o3I9Xv8l2r2F6krjpTDJd0jcv5UwtyNRYRR1JM7dUndk6Rf3zbt0WNfL3mOCx5OptiH6U8+Mg0IoLJczpJKVSQrkG2xdpgNiYHlBSezGsMAGfkUgbW+4TDGPyObFsUOysqcwvNsaiUkv+xmDg2phOHuxpLjfYHikDdHuIkmCThNDpBqwZHjYCVGz3sPkuSwNtCRdpOLhBAWpsT3w/IO3X7a7zpwlt20393b/+lu575H6YN7blIN+VUhRGSOlFD2iO/N05tiBnTZDegEmn82aZ/cpfeVFES282nGVMVjRSmA1i1FcRiLGh5eiVeerBkwMlTxU=
  on:
    tags: true