language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ./keithley2600
# command to run tests
script:
- echo "skipping tests"