language: python
python:
- '2.7'
- '3.6'
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install .
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  password:
    secure: GDK4adO+2r+abTTDcx54F+snWfyO/+oI/Pc/n1yv0tszd0jfop5jUY7Ys5Es2PTNbvcv6czU2fcufl9A6nlFGeHgjCfgWSLlL8UzVYHfIFOTqEJV9BUe39x5iUS8KKbzNzD0n4sm6VXodavxwZJ5Kpr9kFuu5vfRU9tPv8ZWvQd+jYQGJAIByGE1NjaoHj5ulxKqcSwLmZxxorN5FWE3sMK6kehe17I0hOuuM5ao0RETBr3QZFDfaXYIZ8fq+TDDXMKXnUO69RPBGvzxISK3eTN62qBvqCc9X1NprWY6b7JlffvFtSq16XrvSemYHMqOYqOEGxxX9IN5odpOQPo99NrT6JuJfCuXgSemmo5fmj719ZQ1DPLQMw4j71sfOLQYIE07z75KhqY1hes4Jx8nD9EzB8QGZYpBRkFdDSXKsLwDOJFQFXnGIrZdK3lrXTdMkhVHJgzIKLYW46vBnejVd7s+nzO/YntPb/VcKN7xfyE2glve+PNrjqAtzhSHpZPwPse1ty6MGAXLJs3q5Cz6d+dyC6e/YiTSUHGPDD28Wv9e0xfaA2HtLena1nkreD7kXxDduf9gwz7wNjLwXipmPLU/RZ/yg2Y4uQG7arW4yItNu+ST4wKXbYBHHEEFq+zwh5DPr0aqDQiqg+a0wpW7rLxoPpdADHdk8H2jeB/0VEI=
  on:
    tags: true
