language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - echo "skipping tests"

deploy:
  provider: pypi
  user: SamSchott
  skip_existing: true
  password:
    secure: lI3TeHtqzCWAWVC/4+eyI9BjwTW2k3JJ7AGZTSMCs09UK791nZlfeapCU5V4h75hSpc2rm7owEncn/0HtVGtND2NhchBFe18GQPFZyPvdLM563aWN2v+8EF8iZP0TNbU3PrWx8JsjRR4mEIx+ndYDefewg1L+2MqunpwhdU9FprpcpIIzt2BmCierH+dtPLQ9gwyFA30j/LeFONaR8dwZe6UI5Kv4n0lrJdpx772LsvrTi/OzSiTJl6qgDQiyocLtaoHeivUYjouDhus6wgdbOaw7EZDmJARhNqyX/i/f/c3Hpf3CXXGGOi81ATLDDuLBytT8M6a/XOrcyiauo5JVTEbmwBCw2Tb2r+yBfvW115mJT8p1bma7l/f8Ls6AXGxn3m9sRMCes4PQs/m0XuEFFNT7REeZkue/4iOXQf7Mnnr9yGZcppOZdtrO6gopZcQx5QuP+OwI100UGRnQ6UcQyxs/yKaxTliQrp6zUg/ijRp4UEIzsNhtEuxNlH3PvMRpQlrddIAZwXxs2isxs2fCd5MgFp0zYXtJn/ciflmfYaJw9M8FRFkFGRCgx0x7mlW2JThbcwVbRwgwl8n/fh4GN3WFmGqsLAjfg4mbG+SRfT82VsRR40p77SSTRZ9oq0fMQPKVqFYI4edTgsT+NWY1KcHmr0hTixCUDNMTaPHlV4=
  on:
    tags: true
